source "http://rubygems.org"

gem "rails", "2.3.5"
gem 'mysql'

gem "will_paginate"
gem "authlogic"
gem "searchlogic"
gem "bcrypt-ruby", ">=2.0.5", :require => "bcrypt"
gem "acts-as-taggable-on"
gem "awesome_nested_set"
gem "friendly_id"
gem "sanitize"
gem 'paperclip'
gem 'tiny_mce'
gem 'fleakr'
gem 'overlord'
gem "uploader"
#gem "uploader", :path => "~/projects/uploader"

gem "babelphish"
gem 'muck-engine', :require => 'muck_engine'
gem 'muck-users', :require => 'muck_users'
gem 'muck-activities', :require => 'muck_activities'
gem 'muck-solr', :require => 'acts_as_solr'
gem 'muck-comments', :require => 'muck_comments'

if RUBY_VERSION < '1.9'
  gem "ruby-debug", ">= 0.10.3"
end

gem 'shoulda'
gem 'factory_girl'



